Accept Elliptic Curve (EC)  private key
mindee/origamindee pull request #7
Opened 2023-01-27 02:20 UTC by ymalmaguer

In
signature.rb:95
` unless (key.is_a?(OpenSSL::PKey::RSA) || key.is_a?(OpenSSL::PKey::EC))
                raise TypeError, "A OpenSSL::PKey::RSA object must be passed."
            end
`

2023-01-31 02:33 UTC, ymalmaguer commented
#7 Pull Request allows algorithms based on Elliptic Curve to be used, it has already been tested and is in use. Since this Fork is being maintained, we are interested in being able to use it when the pull request is made

2023-01-31 10:14 UTC, ianardee requested changes
Code looks good. Can you add a unit test for it please?

2023-01-31 19:27 UTC, ymalmaguer commented
Yes, we will make this.

2023-01-31 20:19 UTC, ymalmaguer commented
We don't have much experience doing unit tests. it's called **test_ec**

2023-02-01 12:17 UTC, ianardee commented
Great, thank you :-)

I will test on my machine to make sure everything works properly.

2023-02-02 02:51 UTC, ymalmaguer commented
You're welcome, we hope it works correctly ;-)

2023-02-07 21:01 UTC, ymalmaguer commented
When will you make the margin?

2023-02-08 16:06 UTC, ianardee commented
I've had to format and reinstall my PC, will get to this by the end of the week.

2023-02-08 17:11 UTC, ianardee commented
For whatever reason tests were not running on your PR.

I made some changes and created a new PR. But now, some tests are not passing.

Can you take a look at #8 ?

Thanks

2025-02-25 09:04 UTC, closed without merging